[package]
name = "krdoc"
version = "0.1.0"
edition = "2021"
authors = ["https://github.com/thawkins"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
